name: Build project

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker Image
        run: docker build -t ghcr.io/derkoe/rust-webapp .
      - name: Push image to ghcr.io
        if: ${{ github.event_name != 'pull_request'}}
        run: |
          echo ${{ secrets.GHCR_PASSWORD }} | docker login ghcr.io -u ${{ secrets.GHCR_USERNAME }} --password-stdin
          docker push ghcr.io/derkoe/rust-webapp
